Markdownで記事を書けるようにする
WORD-COINS/article-template pull request #73
Opened 2023-04-11 10:14 UTC by puripuri2100

#71 を解決するために、

- テンプレート機能を使ってpandocでmd to latexを行う
- CIでmdモードを検知したら変換の前処理を挟む

の2つを実装しました。

以下の理由によりdraftです

- [ ] https://github.com/WORD-COINS/latex-build/pull/27 が通らないとpandocコマンドが使えない
- [ ] CIのテストができていない

2023-04-12 06:43 UTC, puripuri2100 commented
[article-template-test-md.pdf](https://github.com/WORD-COINS/article-template/files/11208034/article-template-test-md.pdf)

2023-04-12 07:02 UTC, YuseiIto approved these changes
良さそうに、みえる(?) パソコンがわからん

2023-04-12 07:19 UTC, YuseiIto requested changes
```
\def\tightlist{}
\def\passthrough#1{#1}
``` 

は `/main.tex`に書かれていないと効力がないので 

```
! Undefined control sequence.
article_build_1  | l.60 \passthrough
article_build_1  |                {\lstinline!main.md!}ファイル内に記事を書きます。.
```
みたいな話になる

2023-04-12 15:56 UTC, puripuri2100 commented
クラスファイルにコマンドを移植し、おそらくOKに
@YuseiIto

2023-04-17 04:49 UTC, YuseiIto approved these changes
治っていることを確認しました!

2023-04-17 07:29 UTC, puripuri2100 commented
mergeします

2023-04-17 07:29 UTC, merged